export default defineAppConfig({
  pages: [
    'pages/home/index',
    'pages/chat/index',
    'pages/chat/list',
    'pages/memory/index',
    'pages/community/index',
    'pages/profile/index',
    'pages/character/detail',
    'pages/quota/buy',
    'pages/quota/result',
    'pages/share/preview',
    'pages/login/index',
  ],
  tabBar: {
    color: '#5A4A4E',
    selectedColor: '#8B4258',
    backgroundColor: '#F1E7E4',
    list: [
      { pagePath: 'pages/home/index', text: '首页', iconPath: 'assets/icons/home.png', selectedIconPath: 'assets/icons/home-active.png' },
      { pagePath: 'pages/chat/list', text: '聊天', iconPath: 'assets/icons/chat.png', selectedIconPath: 'assets/icons/chat-active.png' },
      { pagePath: 'pages/memory/index', text: '记忆', iconPath: 'assets/icons/memory.png', selectedIconPath: 'assets/icons/memory-active.png' },
      { pagePath: 'pages/profile/index', text: '我的', iconPath: 'assets/icons/profile.png', selectedIconPath: 'assets/icons/profile-active.png' },
    ],
  },
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#FFFBF8',
    navigationBarTitleText: '剧本杀',
    navigationBarTextStyle: 'black',
  },
  networkTimeout: {
    request: 10000,
    downloadFile: 10000,
    uploadFile: 10000,
    connectSocket: 10000,
  },
  sitemapLocation: 'sitemap.json',
  lazyCodeLoading: 'requiredComponents',
});
